<html> <!-- #A3D0F8 -->
	<body style="color: #000; font-size: 16px; text-decoration: none; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #efefef;">
		
		<div id="wrapper" style="max-width: 600px; margin: auto auto; padding: 20px;">
			
			<div id="logo" style="">
			<style>
			table, th, td {
			border: 1px solid black;
			border-collapse: collapse;
			padding:10px;
			}
			</style>
				
			</div>
				
			<div id="content" style="font-size: 16px; padding: 25px; background-color: #fff;
				moz-border-radius: 10px; -webkit-border-radius: 10px; border-radius: 10px; -khtml-border-radius: 10px;
				border-color: #A3D0F8; border-width: 4px 1px; border-style: solid;">
              
				<center><h1 style="margin: 0px;"><a href="https://vwits.in/" target="_blank"><img style="max-height: 75px;" src="http://beststickers.net/image/cache/catalog/products/volkswagen/small/vw-blue-flat-logo-round-domed-emblem-stickers-decal-2800x1600.jpg"></a></h1></center>
              
				<h1 style="font-size: 22px;"><center>Account is Verified  </center></h1>
				
				<p>Hi ${user.customer.fname},</p>
              <p>
                Congratulations...!
              </p>

					 <p>Your Account is Verified.Below You Can Find Your Account Details </p>
					 <table style="padding:10px">
					 <tr>
					 <td>Account No </td> 
					 <td>${user.accountnumber} </td>
					 </tr>
					 <tr>
					 <td>User ID </td> 
					 <td>${user.userid} </td>
					 </tr>
					 <tr>
					 <td>Account Type </td> 
					 <td>${user.accountType} </td>
					 </tr
					  <tr>
					 <td>Login Password </td> 
					 <td>${user.loginPassword} </td>
					 </tr
					  <tr>
					 <td>Transection Password </td> 
					 <td>${user.transectionPassword} </td>
					  </table>
					 
				<p>Respectfully,</p>
				<p>VW bank</p>
                  


                  
                  </center>
                  </div>
				
      
     		
				
			</div>
  
	
	</body>
</html>