<html> <!-- #A3D0F8 -->
	<body style="color: #000; font-size: 16px; text-decoration: none; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #efefef;">
		
		<div id="wrapper" style="max-width: 600px; margin: auto auto; padding: 20px;">
			
			<div id="logo" style="">
				
			</div>
				
			<div id="content" style="font-size: 16px; padding: 25px; background-color: #fff;
				moz-border-radius: 10px; -webkit-border-radius: 10px; border-radius: 10px; -khtml-border-radius: 10px;
				border-color: #A3D0F8; border-width: 4px 1px; border-style: solid;">
              
				<center><h1 style="margin: 0px;"><a href="https://vwits.in/" target="_blank"><img style="max-height: 75px;" src="http://beststickers.net/image/cache/catalog/products/volkswagen/small/vw-blue-flat-logo-round-domed-emblem-stickers-decal-2800x1600.jpg"></a></h1></center>
              
				<h1 style="font-size: 22px;"><center>Welcome To VW Bank</center></h1>
				
				<p>Hi ${user.fname},</p>
				<p>your customer id is ${user.customerid}<p>
              <p>
                Thank You for registering with VW Banking...!
              </p>
				
				<p>Thank you so much for allowing us to help you with your recent account opening. We are committed to providing our customers with the highest level of service and the most innovative banking products possible.</p>
				<p>We are very glad you chose us as your financial institution and hope you will take advantage of our wide variety of savings, investment and loan products, all designed to meet your specific needs.</p>
				<p>You’re receiving this email because you recently created a new VW Banking account or added a new email address. If this wasn’t you, please ignore this email.</p>

				<p>Respectfully,</p>
				<p>VW bank</p>
                  


                  
                  </center>
                  </div>
				
      
     		
				
			</div>
  

			<div id="footer" style="margin-bottom: 20px; padding: 0px 8px; text-align: center;">
				This email was sent to ${user.email}, which is associated with a VW Banking account. 
			</div>
	
	</body>
</html>